### ISSUE TITLE
Can't use Glint for Jade cloud

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/glint#59]
When trying to distribute images to Jade, it appears to succeed, but the image does not end up there. Can you take a look?

**Comment by rd37** [comment]
It appears to be a certificate verify failure 

from https://gcloudcon.westgrid.ca error [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')] 

Investigate adding exception for westgrid

**Comment by rptaylor** [comment]
No, please don't add an exception - that defeats the purpose of using certificates. Can you just install the Grid Canada CA on the Glint server?
http://www.gridcanada.ca/?q=node/5

**Comment by rd37** [comment]
so the gridcanada CA has always been install on the glint server which is
running on mouse01. I had assumed then that the Jade Http[s] SSL cert must
be a self signed cert.

so all I need is their public signed key so I can add it to mouse01 as a
valid exception ...

**Comment by rptaylor** [comment]
But if the Grid Canada CA is installed, and Jade has a cert signed by Grid Canada, it should be accepted as a valid cert right? I don't understand why the public signed key would need to be added as an exception.

Thanks!

**Comment by rd37** [comment]
Issue is will GridCanada certificates on mouse
