### ISSUE TITLE
option to hide non-project images

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/glint#60]
Once you get to using many remote repositories in Glint, the number of images can become vast. 

At the top of the regular Openstack images page, you can select "Project/ Shared with Me/ Public" to see different categories of image. It would be useful if Glint also allowed this kind of selection, then it would only show e.g. the tenant's images in each of the remote repositories, instead of all the public images in each of the remote repositories.

**Comment by rd37** [comment]
There are three buttons at the top of the glint image distribution page "Project","Shared","Public", are these not enough? or do you these selections for each remote site?

**Comment by rptaylor** [comment]
In "Image Distribution", those 3 buttons don't seem to do anything.

**Comment by rd37** [comment]
Ok, I'll check it out. They seem to work for me in filtering the images made available. i.e., as I click public,shared,project,all ... I get a different list for each. just to double check, which tenant/project on mouse are you in when your moving images around? HEP? or other?

**Comment by rptaylor** [comment]
Atlas tenant is the one where I added credentials.

**Comment by rptaylor** [comment]
Actually it seems to be working as expected.
